<a href="https://colab.research.google.com/github/gangabhavani145/PGD_Practice/blob/main/KNN_LSH_Simple_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer


In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).


In [ ]:
%cd /gdrive

/gdrive


In [ ]:
path = "/gdrive/MyDrive/lsh_assignment_data.csv"

df = pd.read_csv(path)
df

category                                               text
0              tech  tv future in the hands of viewers with home th...
1          business  worldcom boss  left books alone  former worldc...
2             sport  tigers wary of farrell  gamble  leicester say ...
3             sport  yeading face newcastle in fa cup premiership s...
4     entertainment  ocean s twelve raids box office ocean s twelve...
...             ...                                                ...
2220            NaN  cars pull down us retail figures us retail sal...
2221            NaN  kilroy unveils immigration policy ex-chatshow ...
2222            NaN  rem announce new glasgow concert us band rem h...
2223            NaN  how political squabbles snowball it s become c...
2224            NaN  souness delight at euro progress boss graeme s...

[2225 rows x 2 columns]

In [ ]:
train_data = df.iloc[:-10,:]
test_data = df.iloc[-10:,:]

In [ ]:
x_train = train_data['text']
y_train = train_data['category']

In [ ]:
x_test = test_data['text']

In [ ]:
vectorizer = TfidfVectorizer(ngram_range=(2, 3), min_df=10, max_features= 4000)

In [ ]:
tfidf_model = vectorizer.fit(x_train)

In [ ]:
train_data_vector = tfidf_model.transform(x_train)

In [ ]:
print(train_data_vector.shape)


(2215, 4000)


In [ ]:
np.random.seed(0)

w1 = np.random.normal(0, 1, 4000)
print(w1)

w2 = np.random.normal(0, 1, 4000)
print(w2)

w3 = np.random.normal(0, 1, 4000)
print(w3)

w4 = np.random.normal(0, 1, 4000)
print(w4)

w5 = np.random.normal(0, 1, 4000)
print(w5)


[ 1.76405235  0.40015721  0.97873798 ... -0.03057244  1.57708821
 -0.8128021 ]
[ 0.61334917  1.84369998  0.27109098 ... -0.20273458 -0.25786648
  0.07081452]
[ 0.99784476  0.26008072  0.92506562 ... -1.9974298  -0.03192091
  0.22396576]
[ 0.94550839  0.42292354 -1.17568    ...  1.41938754  0.74710667
 -0.10630249]
[-1.96265255 -0.83403203  1.99383675 ... -0.05725925 -1.05893126
 -0.32652844]


In [ ]:
train_data_array_vector = pd.DataFrame(train_data_vector.toarray())
train_data_array_vector = np.array(train_data_array_vector)
print(train_data_array_vector)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
test_data_vector = vectorizer.transform(x_test)
test_data_vector.shape

(10, 4000)

In [ ]:
test_data_array_vector = pd.DataFrame(test_data_vector.toarray())
test_data_array_vector = np.array(test_data_array_vector)
print(test_data_array_vector)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.06236649 0.         0.        ]
 [0.         0.         0.         ... 0.13429259 0.         0.        ]]


In [ ]:
rows, cols = train_data_array_vector.shape

hash_table = {}
hash_function = []

def hash_func(w1, w2, w3, w4, w5, train_data_array_vector):
  
  
  for i in range(rows):
    hash_function.clear()

    if (np.dot(w1, train_data_array_vector[i])) > 0 :
      hash_function.append(1)
    else:
      hash_function.append(-1)

    if (np.dot(w2, train_data_array_vector[i])) > 0 :
      hash_function.append(1)
    else:
      hash_function.append(-1)

    if (np.dot(w3, train_data_array_vector[i])) > 0 :
      hash_function.append(1)
    else:
      hash_function.append(-1)

    if (np.dot(w4, train_data_array_vector[i])) > 0 :
      hash_function.append(1)
    else:
      hash_function.append(-1)

    if (np.dot(w5, train_data_array_vector[i])) > 0 :
      hash_function.append(1)
    else:
      hash_function.append(-1)

    if tuple(hash_function) in hash_table.keys():
      hash_table[tuple(hash_function)].append(i)

    if tuple(hash_function) not in hash_table.keys():
      hash_table[tuple(hash_function)] = [i]

  return hash_table


In [ ]:
print(hash_func(w1, w2, w3, w4, w5, train_data_array_vector))

{(-1, 1, 1, -1, 1): [0, 36, 110, 113, 139, 169, 198, 278, 295, 412, 512, 549, 565, 573, 574, 688, 696, 712, 839, 887, 977, 1021, 1071, 1185, 1227, 1243, 1266, 1273, 1381, 1383, 1433, 1463, 1495, 1500, 1503, 1526, 1550, 1584, 1814, 1849, 1864, 2032, 2040, 2051, 2131, 2137, 2151], (1, 1, 1, 1, 1): [1, 28, 54, 74, 92, 117, 118, 135, 146, 168, 172, 205, 242, 334, 388, 449, 521, 531, 532, 533, 540, 576, 615, 616, 655, 722, 781, 892, 935, 1087, 1091, 1140, 1210, 1220, 1274, 1335, 1343, 1358, 1379, 1430, 1564, 1569, 1727, 1785, 1811, 1829, 1840, 1898, 1938, 1949, 1994, 2030, 2083, 2140, 2208], (1, -1, -1, -1, -1): [2, 27, 32, 68, 73, 219, 230, 234, 244, 346, 399, 400, 415, 479, 496, 519, 558, 670, 687, 737, 758, 760, 773, 817, 880, 889, 922, 932, 952, 1049, 1095, 1126, 1156, 1169, 1201, 1365, 1396, 1446, 1513, 1557, 1588, 1624, 1653, 1668, 1703, 1728, 1729, 1787, 1792, 1796, 1870, 1879, 1893, 2069, 2074, 2135, 2176], (-1, 1, -1, -1, -1): [3, 18, 185, 186, 195, 314, 326, 398, 424, 571, 604, 64

In [ ]:
len(hash_table)

32

In [ ]:
test_query_label = []
for i in range(10):
  query = test_data_array_vector[i]
  # print(query)
  hash_function2 = []
  hash_function2.clear()

  if (np.dot(w1, query)) > 0: 
      hash_function2.append(1)
  else:
      hash_function2.append(-1)

  if (np.dot(w2, query)) > 0:  
      hash_function2.append(1)
  else:
      hash_function2.append(-1)
  if (np.dot(w3, query)) > 0:  
      hash_function2.append(1)
  else:
      hash_function2.append(-1)

  if (np.dot(w4, query)) > 0:  
      hash_function2.append(1)
  else:
      hash_function2.append(-1)

  if (np.dot(w5, query)) > 0:  
      hash_function2.append(1)
  else:
      hash_function2.append(-1)
  
  
  NN_indices = hash_table.get(tuple(hash_function2))

  cosine_similarity = []
  cosine_similarity.clear()

  for index in NN_indices:
    # cos_sim = (np.dot(query, train_data_array_vector[i]))/(np.linalg.norm(query)*np.linalg.norm(train_data_array_vector[i]))
    cos_sim = np.dot(query, train_data_array_vector[index])
    cosine_similarity.append([index, cos_sim])
 
  cosine_similarity.sort(key= lambda x: x[1], reverse=True)
  # print(cosine_similarity)
  k_nearrest_neighbors = cosine_similarity[:11]
  # print(k_nearrest_neighbors)
  

  k_nearrest_neighbors_indices = []
  k_nearrest_neighbors_indices.clear()
  for i in range(len(k_nearrest_neighbors)):
    k_nearrest_neighbors_indices.append(k_nearrest_neighbors[i][0])
  # print(k_nearrest_neighbors_indices)


  test_label = []
  labels_dict = dict()
  
  for ind in k_nearrest_neighbors_indices:
    label = y_train[ind]
    test_label.append(label)

  # print(test_label)
  for l in test_label:
    labels_dict[l] = test_label.count(l)
  # print(labels_dict)

  test_query_label.append(max(labels_dict, key= labels_dict.get))

print(np.array(test_query_label))


['tech' 'entertainment' 'tech' 'tech' 'business' 'business' 'politics'
 'entertainment' 'politics' 'sport']
